apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

images:
  - name: ghcr.io/OWNER/civicpulse-backend
    newName: civicpulse-backend
    newTag: dev
  - name: ghcr.io/OWNER/civicpulse-frontend
    newName: civicpulse-frontend
    newTag: dev

replicas:
  - name: backend
    count: 2
  - name: frontend
    count: 2

